In [2]:
! pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 47.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 83.8 MB/s eta 0:00:00


In [4]:
from transformers import pipeline

In [5]:
classifier=pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [6]:
classifier("This library is good enough")

[{'label': 'POSITIVE', 'score': 0.9998718500137329}]

In [7]:
classifier("But these toilet are not too much hygeinic ")

[{'label': 'NEGATIVE', 'score': 0.9982019662857056}]

In [10]:
sents=["The location is great","Area is not so good","Facility are good enough","AC are not too much cooling"]
result=classifier(sents)

In [13]:
for i,j in zip(sents,result):
  print(f"Sentence is: {i} and Result of this Sentence is :{j}")

Sentence is: The location is great and Result of this Sentence is :{'label': 'POSITIVE', 'score': 0.9998282194137573}
Sentence is: Area is not so good and Result of this Sentence is :{'label': 'NEGATIVE', 'score': 0.9997825026512146}
Sentence is: Facility are good enough and Result of this Sentence is :{'label': 'POSITIVE', 'score': 0.9998568296432495}
Sentence is: AC are not too much cooling and Result of this Sentence is :{'label': 'NEGATIVE', 'score': 0.999517560005188}


In [14]:
classifier2=pipeline("sentiment-analysis",model="nlptown/bert-base-multilingual-uncased-sentiment")

In [15]:
classifier2("This Library is good enough but toilet and AC are not so much good")

[{'label': '3 stars', 'score': 0.6201649904251099}]

In [18]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
#these two work as the blueprint of the model
#1. First one is used for the tokenize the sentences with respect to which model is chosen and for the different-different purpose the model
#Would also be changes countinuously.....

In [19]:
model_name="nlptown/bert-base-multilingual-uncased-sentiment"  #chose the which model you want for which type of task.

In [20]:
#this model is available on the pytorch so we use "from_pt" to import this model in the tensorflow
model=TFAutoModelForSequenceClassification.from_pretrained(model_name,from_pt=True)  #we are training model which we want from the model we select for our purpose
tokenizer=AutoTokenizer.from_pretrained(model_name)  #we are training the tokenizer according to us which we model for which purpose we select
classifier_model=pipeline("sentiment-analysis",model=model,tokenizer=tokenizer)   #now give the model and tokenizer according to your model which you select.

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [21]:
classifier_model("Hey! This is very beautiful sights from your side")

[{'label': '5 stars', 'score': 0.8738948702812195}]

#  Now  See the How different- different tokenizer works

In [23]:
#now take any different model for the tokenizer
model_name="distilbert-base-uncased-finetuned-sst-2-english"
model=TFAutoModelForSequenceClassification.from_pretrained(model_name,from_pt=True)
tokenizer=AutoTokenizer.from_pretrained(model_name)


All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [25]:
tokens=tokenizer("Hey! You are such beautiful and I come to know your id @ritesh92")

In [27]:
tokens
#here input_ids are the indexes of the tokens in the corpus of that perticular model

{'input_ids': [101, 4931, 999, 2017, 2024, 2107, 3376, 1998, 1045, 2272, 2000, 2113, 2115, 8909, 1030, 17105, 2232, 2683, 2475, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [32]:
## we can also customize the tokenizer according to us
tf_batch=tokenizer(
    ["Hey ! You are the very beautiful"],
    truncation=True,
    padding=True,
    max_length=512,
    return_tensors="tf"
)

In [33]:
tf_batch

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4931,  999, 2017, 2024, 1996, 2200, 3376,  102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}